version: "3.3"

services:
  orders_db:
    container_name: orders_db
    hostname: orders_db
    image: postgres:13.3
    restart: always
    user: root
    networks:
      - kafka-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - "5434:5432"

  orders_db_migrations:
    container_name: orders_db_migrations
    build: ./
    command: /bin/sh -c "/usr/local/bin/goose postgres up -dir ./migrations"
    networks:
      - kafka-net
    depends_on:
      - orders_db

  orders_service:
    container_name: orders_service
    build: ./
    command: /bin/sh -c "/usr/local/bin/orders"
    networks:
      - kafka-net
    depends_on:
      - redis
      - orders_db
      - orders_db_migrations

  redis:
    image: 'bitnami/redis:latest'
    restart: always
    ports:
      - '6381:6379'
    environment:
      - REDIS_PASSWORD=redis_pass
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge